services:
  - type: web
    name: astro-api
    env: docker
    plan: free
    dockerfilePath: ./docker/Dockerfile
    startCommand: "/app/wsgi-entrypoint.sh"
    envVars:
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: "astro-api.onrender.com"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: POSTGRES_DB
        value: "astro_db"
      - key: POSTGRES_USER
        value: "astro_user"
      - key: POSTGRES_PASSWORD
        value: "replace_me_later"
      - key: POSTGRES_HOST
        value: "astro-db"
      - key: POSTGRES_PORT
        value: "5432"

  - type: pserv
    name: astro-db
    env: docker
    image: postgres:15
    plan: free
    envVars:
      - key: POSTGRES_DB
        value: "astro_db"
      - key: POSTGRES_USER
        value: "astro_user"
      - key: POSTGRES_PASSWORD
        value: "replace_me_later"