name: AstroNO
services:
  api:
    build:
      context: ../src
      dockerfile: ../docker/Dockerfile
    volumes:
      - ../src:/app
    entrypoint: /app/wsgi-entrypoint.sh
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DJANGO_DEBUG
      - DJANGO_SECRET_KEY
      - DJANGO_ALLOWED_HOSTS
      - DJANGO_BASE_URL
      - DJANGO_CSRF_TRUSTED_ORIGINS
      - DJANGO_SUPERUSER_USERNAME
      - DJANGO_SUPERUSER_EMAIL
      - DJANGO_SUPERUSER_PASSWORD
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - DJANGO_DEBUG
      - DJANGO_SECRET_KEY
      - DJANGO_ALLOWED_HOSTS
      - DJANGO_BASE_URL
      - DJANGO_CSRF_TRUSTED_ORIGINS
      - DJANGO_SUPERUSER_USERNAME
      - DJANGO_SUPERUSER_EMAIL
      - DJANGO_SUPERUSER_PASSWORD
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - "5432:5432"

volumes:
  postgres_data: