name: AstroNO
services:
  api:
    build:
      context: ../src
      dockerfile: ../docker/Dockerfile
    volumes:
      - ../src:/app
      - static:/app/static
      - media:/app/media
    entrypoint: /app/wsgi-entrypoint.sh
    ports:
      - "8000:8000"
    env_file:
      - "../src/.env"
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - "../src/.env"
    ports:
      - "5432:5432"
  
  nginx:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/prod:/etc/nginx/conf.d
      - static:/app/static
      - media:/app/media
    depends_on:
      - db
      - api

volumes:
  postgres_data:
  static:
  media:
