# Generated by Django 5.2.6 on 2025-10-14 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_event_end_after_start_event_end_after_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='status',
            field=models.CharField(choices=[('C', 'Confirmed'), ('U', 'Unconfirmed')], default='C', max_length=1),
        ),
    ]
