# Generated by Django 5.2.6 on 2025-10-15 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_registration_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='student_whatsapp_number',
            field=models.CharField(default='nigga', max_length=100),
            preserve_default=False,
        ),
    ]
