# Generated by Django 5.2.6 on 2025-10-15 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_registration_student_whatsapp_number'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together=set(),
        ),
    ]
