# Generated by Django 5.2.6 on 2025-10-15 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_registration_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='status',
            field=models.CharField(choices=[('C', 'Confirmed'), ('U', 'Unconfirmed')], default='U', max_length=1),
        ),
    ]
